### ISSUE TITLE
prediction.getDescription() is not available

### ISSUE THREAD

**Issue by Satish2804** [doomtrooper/GoogleAutoCompleteWithRecyclerView#3]

**Comment by deva11** [comment]
No inbuilt function (getDescription) is available is the class AutocompletePrediction.class

**Comment by parthjdabhi** [comment]
getDescription is deprecated as mentioned on Google docs.

getDescription() is now deprecated. Please use getFullText(), getPrimaryText(), and/or getSecondaryText() to retrieve the full or partial description, getMatchedSubstrings() is now deprecated. Please use getFullText() to format matches more easily. https://developers.google.com/android/guides/releases

**Comment by doomtrooper** [comment]
closing as @parthjdabhi is right.
